ClearExchange()
ResetAccounts()

SetExchangeSession(HNX, ATO)
SetGatewaySession(HNX, ATO)
SetORSSession(HNX, ATO)

ord0 = Place(0001000001, AAA, Buy, ATO, 15000, 100)
Assert(ord0.status, true)
count = CountOrderDetail(ord0.msg)
Assert(count, 1)
status = GetOrderStatus(ord0.msg)
Assert(status, New)

ord1 = Replace(ord0.msg, 15500, 200)
Assert(ord1.status, true)
count = CountOrderDetail(ord0.msg)
Assert(count, 3)
status = GetOrderStatus(ord1.msg)
Assert(status, New)

result = Cancel(ord1.msg)
Assert(result.status, true)
count = CountOrderDetail(ord1.msg)
Assert(count, 7)
status = GetOrderStatus(ord1.msg)
Assert(status, Canceled)

ord2= Place(0001000001, AAA, Buy, ATO, 15000, 100)
Assert(ord2.status, true)
count = CountOrderDetail(ord2.msg)
Assert(count, 1)
status = GetOrderStatus(ord2.msg)
Assert(status, New)

ord3= Place(0001000002, AAA, Sell, ATO, 15000, 100)
Assert(ord3.status, true)
count = CountOrderDetail(ord3.msg)
Assert(count, 1)
status = GetOrderStatus(ord3.msg)
Assert(status, New)

SetExchangeSession(HNX, OPEN)
SetGatewaySession(HNX, OPEN)
SetORSSession(HNX, OPEN)

count = CountOrderDetail(ord2.msg)
Assert(count, 2)
status = GetOrderStatus(ord2.msg)
Assert(status, Expired)

count = CountOrderDetail(ord3.msg)
Assert(count, 2)
status = GetOrderStatus(ord3.msg)
Assert(status, Expired)
